version: "3.7"
services:

  ipfs-node:
    image: linuxserver/ipfs
    restart: unless-stopped
    network_mode: service:vpn-sidecar
    depends_on:
      - vpn-sidecar
    volumes:
      - ipfs-node-data-volume:/config
      - downloads-volume:/downloads

  web-proxy:
    image: dperson/nginx
    restart: unless-stopped
    environment:
      - PROXY=http://ipfs-node:5001;/ # for API & web UI
      - STREAM=8080;ipfs-node:8080    # for IPFS gateway
    ports:
      - 5001:80/tcp
      - 8080:8080/tcp
    links:
      - vpn-sidecar:ipfs-node
    depends_on:
      - ipfs-node
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    networks:
      - default
      - isolated_ipfs_network

  vpn-sidecar:
    image: dperson/openvpn-client
    restart: unless-stopped
    networks:
      - isolated_ipfs_network
    cap_add:
      - NET_ADMIN
    read_only: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - openvpn-client-config-volume:/vpn
    environment:
      FIREWALL: ""
      VPNPORT: "4001;udp"   # port forwarding for ipfs-node
      VPNPORT_2: "4001;tcp" # update /ipfs/config in the ipfs container if these are changed
      OTHER_ARGS: "--mute-replay-warnings" # optional
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 # for raspberry pi compatibility?

volumes:
  ipfs-node-data-volume: # go-ipfs application files - change to a persistent location
    driver_opts:
        type: tmpfs
        device: tmpfs
  downloads-volume: # (optional) file download location - change to a persistent location
    driver_opts:
        type: tmpfs
        device: tmpfs
  openvpn-client-config-volume: # read-only location of *.ovpn
    driver: local
    driver_opts:
        o: bind
        type: none
        device: "$PWD/openvpn/"   

networks:
  default:
  isolated_ipfs_network:
